### ISSUE TITLE
JS client as an npm package

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/microraiden#136]
Maybe also add the cooperative close logic from main.js to the MicroRaiden class.
Readme file with documentation

**Comment by loredanacirstea** [comment]
fixed in https://github.com/raiden-network/microraiden/pull/151

**Comment by andrevmatos** [comment]
Will keep it closed, as everything is ready, but the package still isn't published actually. Will do together with the release probably.
